# -*- coding: utf-8 -*-
"""Job_market_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ntEp5uXUgDORzFEc0pd4-p2I9rzMNE-s
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/fresher_hiring_india_dataset.csv')

df.head()

df.shape

df.info()

"""##Check null value"""

df.isnull().sum()

"""##Drop null features"""

df.drop(columns=['interview_rounds', 'offered_salary_inr', 'linkedin_premium'], inplace=True)

"""##Check duplicate value"""

df.duplicated().sum()

"""##Summary"""

df.describe()

"""#EDA"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))

sns.countplot(
    data=df,
    x='hiring_stage',
    order=df['hiring_stage'].value_counts().index
)

plt.xticks(rotation=45)
plt.title('Hiring Stage Distribution Shows Candidate Funnel Status')
plt.tight_layout()  # Prevents label overlap
plt.show()

plt.figure(figsize=(10, 6))

pd.crosstab(df['gender'], df['hiring_stage']).plot(
    kind='bar',
    stacked=False
)

plt.title('Hiring Stage Comparison Across Gender Groups')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

fig = plt.figure(figsize=(10,6))
sns.histplot(data=df, x='age', bins=20, kde=True)
plt.title('Candidate Age Distribution Highlights Applicant Experience Range')
plt.show()

fig = plt.figure(figsize=(10,6))
sns.boxplot(data=df, x='hiring_stage', y='age')
plt.xticks(rotation=45)
plt.title('Age Variation Across Hiring Stages')
plt.show()

fig = plt.figure(figsize=(10,6))
sns.histplot(data=df, x='cgpa', bins=20, kde=True)
plt.title('CGPA Distribution Shows Academic Strength of Candidates')
plt.tight_layout()
plt.show()

fig = plt.figure(figsize=(10,6))
sns.boxplot(data=df, x='hiring_stage', y='cgpa')
plt.xticks(rotation=45)
plt.title('CGPA Comparison Across Hiring Outcomes')
plt.tight_layout()
plt.show()

fig = plt.figure(figsize=(10,6))
sns.countplot(data=df, x='backlogs', hue='hiring_stage')
plt.title('Backlogs Impact on Candidate Hiring Stage')
plt.tight_layout()
plt.show()

fig = plt.figure(figsize=(10,6))
sns.countplot(data=df, y='college', order=df['college'].value_counts().head(10).index)
plt.title('Top Colleges Contributing Maximum Candidates')
plt.tight_layout()
plt.show()

fig = plt.figure(figsize=(10,6))
sns.countplot(data=df, y='degree', order=df['degree'].value_counts().index)
plt.title('Degree-Wise Candidate Distribution')
plt.tight_layout()
plt.show()

fig = plt.figure(figsize=(10,6))
sns.countplot(data=df, y='branch', order=df['branch'].value_counts().head(10).index)
plt.title('Branch-Wise Candidate Demand Pattern')
plt.tight_layout()
plt.show()

fig = plt.figure(figsize=(10,6))
sns.countplot(data=df, y='sector', order=df['sector'].value_counts().index)
plt.title('Sector-Wise Hiring Application Distribution')
plt.tight_layout()
plt.show()

fig = plt.figure(figsize=(10,6))
sns.countplot(data=df, y='job_role', order=df['job_role'].value_counts().head(10).index)
plt.title('Most Applied Job Roles Among Candidates')
plt.tight_layout()
plt.show()

fig = plt.figure(figsize=(10,6))
sns.countplot(data=df, x='work_type', hue='hiring_stage')
plt.title('Work Type Preference Compared With Hiring Stage')
plt.tight_layout()
plt.show()

fig = plt.figure(figsize=(10,6))
sns.countplot(data=df, y='job_location', order=df['job_location'].value_counts().head(10).index)
plt.title('Top Job Locations by Candidate Applications')
plt.tight_layout()
plt.show()

fig = plt.figure(figsize=(10,6))
sns.boxplot(data=df, x='hiring_stage', y='response_time_days')
plt.xticks(rotation=45)
plt.title('Response Time Difference Across Hiring Stages')
plt.tight_layout()
plt.show()

fig = plt.figure(figsize=(10,6))
sns.boxplot(data=df, x='referral_applied', y='response_time_days')
plt.title('Referral Impact on Company Response Time')
plt.tight_layout()
plt.show()

fig = plt.figure(figsize=(10,6))
df['application_date'] = pd.to_datetime(df['application_date'])
df.groupby(df['application_date'].dt.year).size().plot(kind='line', marker='o')
plt.title('Year-Wise Application Trend Shows Hiring Activity Growth')
plt.show()

fig = plt.figure(figsize=(10,6))
corr = df.select_dtypes(include='number').corr()
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap Shows Numeric Feature Relationships')
plt.tight_layout()
plt.show()

